config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'flights#index'
  resources :flights do
    resources :bookings
  end
  get 'transactions', to: 'bookings#index', as: :transactions
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, class_name: "Flight", foreign_key: "from_airport_id"
    has_many :arriving_flights, class_name: "Flight", foreign_key: "to_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :from_airport, class_name: "Airport"
    belongs_to :to_airport, class_name: "Airport"
    has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    # Set up the Spreedly enviornment using the environment key and access secret
    env = Spreedly::Environment.new(ENV["ENV_KEY"], ENV["ACCESS_SECRET"])

    # Retrieve the first 20 transactions (paginated resource)
    transactions = env.list_transactions
    # If the next page of resources exists
    until env.list_transactions(transactions.last.token).empty?
      next_set = env.list_transactions(transactions.last.token)
      transactions += next_set
    end
    @transactions = transactions
  end
  
  def show
    @booking = Booking.find(params[:id])
  end
  
  def new
    @flight = Flight.find(params[:flight_id])
    @booking = @flight.bookings.build
    @num_passengers = params[:num_passengers].to_i
    @total_price = @flight.price * @num_passengers
    
    # If user has just completed filling out the Spreedly Express pop-up form, 
    # then the URL will contain the payment_method_token query parameter
    if params[:payment_method_token]
      # Extract the payment method token from the params (passed as a hidden form field)
      payment_method_token = params[:payment_method_token]
      # Set up the Spreedly enviornment using the environment key and access secret
      env = Spreedly::Environment.new(ENV["ENV_KEY"], ENV["ACCESS_SECRET"])

      # If the user has chosen to make the purchase through Expedia
      if params[:expedia] == "true"
        # Add the test receiver
        receiver = env.add_receiver("test", 
          host_names = "https://spreedly-echo.herokuapp.com", 
          credentials = [
            {
              "name": "app-id",
              "value": 1234,
              "safe": true
            },
            {
              "name": "app-secret",
              "value": 5678
            }
          ])
        # Process the payment transaction
        transaction = env.deliver_to_receiver(receiver.token, # receiver token for the test echo receiver
          payment_method_token,       # payment method token from the query parameters
          url: "https://spreedly-echo.herokuapp.com",
          headers: {"Content-Type" => "application/json"},
          body:
            {amount: @total_price * 100}) # add amount option in cents
      # Otherwise, use the Spreedly test gateway
      else
        # If the use has selected to save their card
        if params[:save_card]
          transaction = env.purchase_on_gateway(ENV["TEST_GATEWAY_TOKEN"], # gateway token for the test API gateway
            payment_method_token,     # payment method token from the query parameters
            @total_price * 100,       # purchase amount converted into cents
            retain_on_success: true)  # retain the payment method if the transaction is successful
        else
          transaction = env.purchase_on_gateway(ENV["TEST_GATEWAY_TOKEN"], # gateway token for the test API gateway
            payment_method_token,     # payment method token from the query parameters
            @total_price * 100)       # purchase amount converted into cents
        end
      end

      if transaction.succeeded?
        @booking.num_passengers = @num_passengers
        @booking.total_price = @total_price
        @booking.transaction_token = transaction.token
        @booking.save
        flash[:success] = "Payment successful!"
        redirect_to flight_booking_path(@flight, @booking)
      else
        flash[:danger] = "Payment failed. Please try again./n #{transaction.message}"
        redirect_to new_flight_booking_path(@flight, num_passengers: @num_passengers)
      end
    end
  end

  def create

    @booking.payment_method_token = params[:payment_method_token]
    @booking.save

    
    # redirect_to flight_booking_path(@flight, @booking) #, payment_method_token: params[:payment_method_token]
    redirect_to root_path
  end

  private
    def booking_params
      params.require(:booking).permit(:num_passengers, :total_price)
    end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    @airport_options = Airport.all.map { |a| ["#{a.code} - #{a.name}", a.id] }
    dates = Flight.all.map { |flight| flight.departure.strftime("%m/%d/%y") }
    @date_options = dates.uniq

    if params[:from_airport] || params[:to_airport]
        @flights = Flight.where(from_airport: Airport.find(params[:from_airport]), 
            to_airport: Airport.find(params[:to_airport]), 
            departure: DateTime.strptime(params[:date], "%m/%d/%y"))
    else        
        @flights = Flight.all
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/index.html.erb
<h2>All Flight Transactions</h2>

<table>
  <tr>
    <th>Transaction Time</th>
    <th>Transaction Token</th>
    <th>Transaction Message</th>
  </tr>

  <% @transactions.each do |transaction| %>
  <tr>
    <td><%= transaction.created_at.strftime("%b %e, %Y at %l:%M %P") %></td>
    <td><%= transaction.token %></td>
    <td><%= transaction.message %></td>
  </tr>

<% end %>
</table>

app/views/bookings/new.html.erb
<h2>Purchase selected flight</h2>

<table>
  <tr>
    <th>Origin</th>
    <th>Destination</th>
    <th>Departing</th>
    <th>Flight Duration</th>
    <th>Price</th>
    <th>Number of Passengers</th>
    <th>Total Cost</th>
  </tr>

  <tr>
    <td><%= @flight.from_airport.code %></td> 
    <td><%= @flight.to_airport.code %></td>
    <td><%= @flight.departure.strftime("%m/%d/%y") %></td>
    <td><%= @flight.duration %></td>
    <td>$<%= @flight.price %></td>
    <td><%= @num_passengers %>
    <td>$<%= @total_price %>
  </tr>
</table><br><br>

<%= form_for [@flight, @booking] do |f| %>
  <% @num_passengers.times do |i| %>
    <%= "Passenger #{i+1}:" %>
    <%# f.label :name %>
    <%# f.text_field :name %><br>
    <%# f.label :email %>
    <%# f.text_field :email %><br>
  <% end %>
<% end %><br>

<form action="/flights/<%= @flight.id %>/bookings/new" id="payment-form">
  <input type="hidden" name="payment_method_token" id="payment_method_token">
  
  <%# Add hidden field to pass num_passengers variable to next screen %>
  <input type="hidden" name="num_passengers" value= <%= @num_passengers %>>

  <input type="checkbox" name="save_card" value="true" checked> Save card for future purchases?<br>

  <input type="checkbox" name="expedia" value="true"> Use Expedia for checkout?<br><br>
  
  <input type="button" value="Checkout" onclick="SpreedlyExpress.openView();">
</form>

<script>
// Initialize Spreedly Express with total cost
SpreedlyExpress.init("ZsZlG3TIExW3qlEs5lOVIj4mEyN", {
  // Additional quotation marks are needed for this to resolve as a string
  "amount": "<%= "$#{@total_price}" %>",
  "company_name": "Spreedly Airlines"
});


// Create a callback function that sends the payment method token to company servers
SpreedlyExpress.onPaymentMethod(function(token, paymentMethod) {

  // Send requisite payment method info to backend
  var tokenField = document.getElementById("payment_method_token");

  tokenField.setAttribute("value", token);

  var masterForm = document.getElementById('payment-form');
  masterForm.submit();
});
</script>

app/views/bookings/show.html.erb
<h2>Your flight booking</h2>


<table>
  <tr>
    <th>Number of Passengers</th>
    <th>Total Cost</th>
    <th>Transaction confirmation</th>
  </tr>

  <tr>
    <td><%= @booking.num_passengers %>
    <td>$<%= @booking.total_price %>
    <td><%= @booking.transaction_token %>
  </tr>
</table><br><br>

<%= link_to "All transactions", transactions_path %>

app/views/flights/index.html.erb
<%= form_tag(flights_path, method: :get) do %>
  <p>Departing from:</p>
  <%= select_tag(:from_airport, options_for_select(@airport_options)) %>

  <p>Arriving at:</p>
  <%= select_tag(:to_airport, options_for_select(@airport_options, selected: "LAX - Los Angeles International Airport")) %>

  <p>Number of passengers:</p>
  <%= select_tag(:num_passengers, options_for_select([[1], [2], [3], [4]])) %>

  <p>Date:</p>
  <%= select_tag(:date, options_for_select(@date_options)) %>
  <br><br>
  
  <%= submit_tag "Search flights" %><br><br>

<% end %>

<table>
  <tr>
    <th>Origin</th>
    <th>Destination</th>
    <th>Departing</th>
    <th>Flight Duration</th>
    <th>Price</th>
    <th>   </th>
  </tr>

  <% @flights.each do |flight| %>
  <tr>
    <td><%= flight.from_airport.code %></td> 
    <td><%= flight.to_airport.code %></td>
    <td><%= flight.departure.strftime("%m/%d/%y") %></td>
    <td><%= flight.duration %></td>
    <td>$<%= flight.price %></td>
    <td><%= link_to "Purchase Flight", new_flight_booking_path(flight, num_passengers: (params[:num_passengers] || 1) ) %></td>
  </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leila Airlines</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%# Load Spreedly Express %>
  <script src="https://core.spreedly.com/iframe/express-2.min.js"></script>
    <h1>Leila Airlines</h1>
    <% flash.each do |message_type, message| %>
      <div><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>